# - *- coding: utf- 8 - *-
print ("Hello World!")
print ("Hello Again")
print ("I like typing this")
print ("This is fun")
print ('Yay! printing')
print ("I'd much rather you 'not'.")
print ('I "said" do not touch this.')
print ("That is great.")
print ("What ever this does, I'll do it to the end.")